config/routes.rb
Rails.application.routes.draw do
  root 'profiles#index'
  resources :profiles, only: [:index] do
    resources :chats, only: [:index, :create] do
      post 'send_message', on: :collection  # Add this line
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  include ActionView::RecordIdentifier
  belongs_to :profile

  enum sent_by: { user: 0, profile: 1 }

  after_create_commit -> { broadcast_created }

  def broadcast_created
    broadcast_append_later_to(
      "#{dom_id(profile)}_messages",
      partial: "messages/message",
      locals: { message: self, scroll_to: true },
      target: "#{dom_id(profile)}_messages"
    )
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  enum gender: { male: 0, female: 1 }
  enum category: { anime: 0, realistic: 1 }

  has_many :messages

  def self.ransackable_attributes(auth_object = nil)
    ["category", "gender"]
  end
end

app/models/server.rb
class Server < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_profile, only: [:index, :send_message]

  def index
    @messages = @profile.messages
  end

  def send_message
    @profile.messages.create(body: params[:body], sent_by: 'user', archived: false)
    ChatApiWorker.perform_async(@profile.id, params[:body])
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_profile
    @profile = Profile.find(params[:profile_id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @q = Profile.ransack(params[:q])
    @profiles = @q.result.page(params[:page]).per(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/index.html.erb
<turbo-frame id="current_profile_chats">
  <%= turbo_stream_from "#{dom_id(@profile)}_messages" %>
  <h1>Chat with <%= @profile.name %></h1>
  <div id="<%= dom_id(@profile) %>_messages">
    <%= render @profile.messages %>
  </div>

  <%= render partial: "messages/form", locals: { profile: @profile } %>
</turbo-frame>

app/views/chats/send_message.turbo_stream.erb
<%= turbo_stream.append "#{dom_id(@profile)}_messages" do %>
  <%= render partial: "messages/message", locals: { message: @profile.messages.last }, scroll_to: true %>
<% end %>
<%= turbo_stream.replace "#{dom_id(@profile)}_message_form" do %>
  <%= render partial: "messages/form", locals: { profile: @profile } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= turbo_frame_tag "#{dom_id(profile)}_message_form" do %>
  <%= form_with(url: send_message_profile_chats_path(profile_id: @profile.id)) do |form| %>
    <%= form.hidden_field :profile_id, value: @profile.id %>
    <%= form.text_field :body, placeholder: 'Type your message...' %>
    <%= form.submit 'Send' %>
  <% end %>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id(message) %>_messages">
  <div class="<%= message.sent_by %>">
    <% if message.sent_by == 'user' %>
      <strong>User:</strong> <%= message.body %>
    <% elsif message.sent_by == 'profile' %>
      <strong><%= message.profile.name %>:</strong> <%= message.body %>
    <% else %>
      <%= message.body %>
    <% end %>
  </div>
</div>

app/views/profiles/index.html.erb
<h1>All Profiles</h1>

<%= search_form_for @q do |f| %>
  <div>
    <%= f.label :gender_eq, 'Gender' %>
    <%= f.select :gender_eq, Profile.genders.to_a.map { |w| [w[0], w[1]] }, { include_blank: true } %>
  </div>
  <div>
    <%= f.label :category_eq, 'Category' %>
    <%= f.select :category_eq, Profile.categories.to_a.map { |w| [w[0], w[1]] }, { include_blank: true } %>
  </div>
  <div>
    <%= f.submit 'Filter' %>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Category</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.gender %></td>
        <td><%= profile.category %></td>
        <td>
          <%= link_to "Start Chat", profile_chats_path(profile_id: profile.id), class: 'btn btn-primary' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @profiles %>